// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Data.Contexts;

#nullable disable

namespace Storage.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20260321125100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Storage.Domain.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerGroupId");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("Storage.Domain.Models.ContainerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabinet")
                        .HasColumnType("int");

                    b.Property<int>("GroupColumn")
                        .HasColumnType("int");

                    b.Property<int>("GroupRow")
                        .HasColumnType("int");

                    b.Property<int>("Shelf")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContainerGroups", (string)null);
                });

            modelBuilder.Entity("Storage.Domain.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lots", (string)null);
                });

            modelBuilder.Entity("Storage.Domain.Models.LotSection", b =>
                {
                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("LotId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("LotSections", (string)null);
                });

            modelBuilder.Entity("Storage.Domain.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("Storage.Domain.Models.Container", b =>
                {
                    b.HasOne("Storage.Domain.Models.ContainerGroup", null)
                        .WithMany("Containers")
                        .HasForeignKey("ContainerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Storage.Domain.Models.Location", "Location", b1 =>
                        {
                            b1.Property<int>("ContainerId")
                                .HasColumnType("int");

                            b1.Property<int>("Cabinet")
                                .HasColumnType("int")
                                .HasColumnName("Cabinet");

                            b1.Property<int>("GroupColumn")
                                .HasColumnType("int")
                                .HasColumnName("GroupColumn");

                            b1.Property<int>("GroupRow")
                                .HasColumnType("int")
                                .HasColumnName("GroupRow");

                            b1.Property<int>("PositionColumn")
                                .HasColumnType("int")
                                .HasColumnName("PositionColumn");

                            b1.Property<int>("PositionRow")
                                .HasColumnType("int")
                                .HasColumnName("PositionRow");

                            b1.Property<int>("Shelf")
                                .HasColumnType("int")
                                .HasColumnName("Shelf");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Storage.Domain.Models.LotSection", b =>
                {
                    b.HasOne("Storage.Domain.Models.Lot", null)
                        .WithMany("LotSections")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storage.Domain.Models.Section", null)
                        .WithMany("LotSections")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storage.Domain.Models.Section", b =>
                {
                    b.HasOne("Storage.Domain.Models.Container", null)
                        .WithMany("Sections")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storage.Domain.Models.Container", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Storage.Domain.Models.ContainerGroup", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("Storage.Domain.Models.Lot", b =>
                {
                    b.Navigation("LotSections");
                });

            modelBuilder.Entity("Storage.Domain.Models.Section", b =>
                {
                    b.Navigation("LotSections");
                });
#pragma warning restore 612, 618
        }
    }
}
